
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using Apps.Models;
using Apps.DAL;
using Apps.Spl.IDAL;
using System;
namespace Apps.Spl.DAL
{
	public partial class Spl_OrdersRepository:BaseRepository<Spl_Orders>,ISpl_OrdersRepository,IDisposable
	{
	    public Spl_OrdersRepository(DBContainer db):base(db)
        {
        
        }
     
	}

}
