
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Spl.IDAL;
using Apps.Models.Spl;
namespace Apps.Spl.BLL
{
	public class Virtual_Spl_ActivesBLL
	{
        [Dependency]
        public ISpl_ActivesRepository m_Rep { get; set; }

		public virtual List<Spl_ActivesModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Spl_Actives> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
				
				a=>a.Title.Contains(queryStr)
				

				|| a.Cont.Contains(queryStr)
				

				|| a.Fors.Contains(queryStr)
				

				
				

				
				

				
				

				
				

				
				

				|| a.Id.Contains(queryStr)
				

				);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<Spl_ActivesModel> CreateModelList(ref IQueryable<Spl_Actives> queryData)
        {

            List<Spl_ActivesModel> modelList = (from r in queryData
                                              select new Spl_ActivesModel
                                              {

													Title = r.Title,

													Cont = r.Cont,

													Fors = r.Fors,

													BeginDate = r.BeginDate,

													EndDate = r.EndDate,

													IsShow = r.IsShow,

													CreateTime = r.CreateTime,

													UpdateTime = r.UpdateTime,

													Id = r.Id,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Spl_ActivesModel model)
        {
            try
            {
			    Spl_Actives entity = m_Rep.GetById(model.Title);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Spl_Actives(); 

				entity.Title = model.Title;

				entity.Cont = model.Cont;

				entity.Fors = model.Fors;

				entity.BeginDate = model.BeginDate;

				entity.EndDate = model.EndDate;

				entity.IsShow = model.IsShow;

				entity.CreateTime = model.CreateTime;

				entity.UpdateTime = model.UpdateTime;

				entity.Id = model.Id;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, Spl_ActivesModel model)
        {
            try
            {
                Spl_Actives entity = m_Rep.GetById(model.Title);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              
				entity.Title = model.Title;

				entity.Cont = model.Cont;

				entity.Fors = model.Fors;

				entity.BeginDate = model.BeginDate;

				entity.EndDate = model.EndDate;

				entity.IsShow = model.IsShow;

				entity.CreateTime = model.CreateTime;

				entity.UpdateTime = model.UpdateTime;

				entity.Id = model.Id;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual Spl_ActivesModel GetById(string id)
        {
            if (IsExists(id))
            {
                Spl_Actives entity = m_Rep.GetById(id);
                Spl_ActivesModel model = new Spl_ActivesModel();
                              
				model.Title = entity.Title;

				model.Cont = entity.Cont;

				model.Fors = entity.Fors;

				model.BeginDate = entity.BeginDate;

				model.EndDate = entity.EndDate;

				model.IsShow = entity.IsShow;

				model.CreateTime = entity.CreateTime;

				model.UpdateTime = entity.UpdateTime;

				model.Id = entity.Id;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
