
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Spl.IDAL;
using Apps.Models.Spl;
namespace Apps.Spl.BLL
{
	public class Virtual_Spl_YouHuiBLL
	{
        [Dependency]
        public ISpl_YouHuiRepository m_Rep { get; set; }

		public virtual List<Spl_YouHuiModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Spl_YouHui> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
				
				a=>a.Id.Contains(queryStr)
				

				|| a.TypeName.Contains(queryStr)
				

				
				

				|| a.YContent.Contains(queryStr)
				

				
				

				
				

				);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<Spl_YouHuiModel> CreateModelList(ref IQueryable<Spl_YouHui> queryData)
        {

            List<Spl_YouHuiModel> modelList = (from r in queryData
                                              select new Spl_YouHuiModel
                                              {

													Id = r.Id,

													TypeName = r.TypeName,

													CreateTime = r.CreateTime,

													YContent = r.YContent,

													Expiry = r.Expiry,

													ShuE = r.ShuE,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Spl_YouHuiModel model)
        {
            try
            {
			    Spl_YouHui entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Spl_YouHui(); 

				entity.Id = model.Id;

				entity.TypeName = model.TypeName;

				entity.CreateTime = model.CreateTime;

				entity.YContent = model.YContent;

				entity.Expiry = model.Expiry;

				entity.ShuE = model.ShuE;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, Spl_YouHuiModel model)
        {
            try
            {
                Spl_YouHui entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              
				entity.Id = model.Id;

				entity.TypeName = model.TypeName;

				entity.CreateTime = model.CreateTime;

				entity.YContent = model.YContent;

				entity.Expiry = model.Expiry;

				entity.ShuE = model.ShuE;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual Spl_YouHuiModel GetById(string id)
        {
            if (IsExists(id))
            {
                Spl_YouHui entity = m_Rep.GetById(id);
                Spl_YouHuiModel model = new Spl_YouHuiModel();
                              
				model.Id = entity.Id;

				model.TypeName = entity.TypeName;

				model.CreateTime = entity.CreateTime;

				model.YContent = entity.YContent;

				model.Expiry = entity.Expiry;

				model.ShuE = entity.ShuE;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
