
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Spl.IDAL;
using Apps.Models.Spl;
namespace Apps.Spl.BLL
{
	public class Virtual_Spl_FranchiseeBLL
	{
        [Dependency]
        public ISpl_FranchiseeRepository m_Rep { get; set; }

		public virtual List<Spl_FranchiseeModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Spl_Franchisee> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
				
				a=>a.Id.Contains(queryStr)
				

				|| a.FranchiseeName.Contains(queryStr)
				

				|| a.FranchiseeType.Contains(queryStr)
				

				|| a.Tel.Contains(queryStr)
				

				|| a.Addr.Contains(queryStr)
				

				|| a.Area.Contains(queryStr)
				

				
				

				|| a.Note.Contains(queryStr)
				

				);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<Spl_FranchiseeModel> CreateModelList(ref IQueryable<Spl_Franchisee> queryData)
        {

            List<Spl_FranchiseeModel> modelList = (from r in queryData
                                              select new Spl_FranchiseeModel
                                              {

													Id = r.Id,

													FranchiseeName = r.FranchiseeName,

													FranchiseeType = r.FranchiseeType,

													Tel = r.Tel,

													Addr = r.Addr,

													Area = r.Area,

													CreateTime = r.CreateTime,

													Note = r.Note,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Spl_FranchiseeModel model)
        {
            try
            {
			    Spl_Franchisee entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Spl_Franchisee(); 

				entity.Id = model.Id;

				entity.FranchiseeName = model.FranchiseeName;

				entity.FranchiseeType = model.FranchiseeType;

				entity.Tel = model.Tel;

				entity.Addr = model.Addr;

				entity.Area = model.Area;

				entity.CreateTime = model.CreateTime;

				entity.Note = model.Note;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, Spl_FranchiseeModel model)
        {
            try
            {
                Spl_Franchisee entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              
				entity.Id = model.Id;

				entity.FranchiseeName = model.FranchiseeName;

				entity.FranchiseeType = model.FranchiseeType;

				entity.Tel = model.Tel;

				entity.Addr = model.Addr;

				entity.Area = model.Area;

				entity.CreateTime = model.CreateTime;

				entity.Note = model.Note;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual Spl_FranchiseeModel GetById(string id)
        {
            if (IsExists(id))
            {
                Spl_Franchisee entity = m_Rep.GetById(id);
                Spl_FranchiseeModel model = new Spl_FranchiseeModel();
                              
				model.Id = entity.Id;

				model.FranchiseeName = entity.FranchiseeName;

				model.FranchiseeType = entity.FranchiseeType;

				model.Tel = entity.Tel;

				model.Addr = entity.Addr;

				model.Area = entity.Area;

				model.CreateTime = entity.CreateTime;

				model.Note = entity.Note;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
