//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Spl.IDAL;
using Apps.Models.Spl;
namespace Apps.Spl.BLL
{
	public class Virtual_Spl_OrdersBLL
	{
        [Dependency]
        public ISpl_OrdersRepository m_Rep { get; set; }

		public virtual List<Spl_OrdersModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Spl_Orders> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.id.Contains(queryStr)
								|| a.UserId.Contains(queryStr)
								|| a.OrderNo.Contains(queryStr)
								|| a.Status.Contains(queryStr)
								|| a.AddressId.Contains(queryStr)
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<Spl_OrdersModel> CreateModelList(ref IQueryable<Spl_Orders> queryData)
        {

            List<Spl_OrdersModel> modelList = (from r in queryData
                                              select new Spl_OrdersModel
                                              {
													id = r.id,
													UserId = r.UserId,
													OrderNo = r.OrderNo,
													Status = r.Status,
													AddressId = r.AddressId,
													CreateTime = r.CreateTime,
													UpdateTime = r.UpdateTime,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Spl_OrdersModel model)
        {
            try
            {
			    Spl_Orders entity = m_Rep.GetById(model.id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Spl_Orders(); 
				entity.id = model.id;
				entity.UserId = model.UserId;
				entity.OrderNo = model.OrderNo;
				entity.Status = model.Status;
				entity.AddressId = model.AddressId;
				entity.CreateTime = model.CreateTime;
				entity.UpdateTime = model.UpdateTime;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, Spl_OrdersModel model)
        {
            try
            {
                Spl_Orders entity = m_Rep.GetById(model.id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.id = model.id;
				entity.UserId = model.UserId;
				entity.OrderNo = model.OrderNo;
				entity.Status = model.Status;
				entity.AddressId = model.AddressId;
				entity.CreateTime = model.CreateTime;
				entity.UpdateTime = model.UpdateTime;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual Spl_OrdersModel GetById(string id)
        {
            if (IsExists(id))
            {
                Spl_Orders entity = m_Rep.GetById(id);
                Spl_OrdersModel model = new Spl_OrdersModel();
                              				model.id = entity.id;
				model.UserId = entity.UserId;
				model.OrderNo = entity.OrderNo;
				model.Status = entity.Status;
				model.AddressId = entity.AddressId;
				model.CreateTime = entity.CreateTime;
				model.UpdateTime = entity.UpdateTime;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
