
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Spl.IDAL;
using Apps.Models.Spl;
namespace Apps.Spl.BLL
{
	public class Virtual_Spl_ProductCategorySBLL
	{
        [Dependency]
        public ISpl_ProductCategorySRepository m_Rep { get; set; }

		public virtual List<Spl_ProductCategorySModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Spl_ProductCategoryS> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
				
				a=>a.Name.Contains(queryStr)
				

				|| a.SupID.Contains(queryStr)
				

				
				

				|| a.Note.Contains(queryStr)
				

				|| a.Id.Contains(queryStr)
				

				);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<Spl_ProductCategorySModel> CreateModelList(ref IQueryable<Spl_ProductCategoryS> queryData)
        {

            List<Spl_ProductCategorySModel> modelList = (from r in queryData
                                              select new Spl_ProductCategorySModel
                                              {

													Name = r.Name,

													SupID = r.SupID,

													Promoted = r.Promoted,

													Note = r.Note,

													Id = r.Id,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Spl_ProductCategorySModel model)
        {
            try
            {
			    Spl_ProductCategoryS entity = m_Rep.GetById(model.Name);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Spl_ProductCategoryS(); 

				entity.Name = model.Name;

				entity.SupID = model.SupID;

				entity.Promoted = model.Promoted;

				entity.Note = model.Note;

				entity.Id = model.Id;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, Spl_ProductCategorySModel model)
        {
            try
            {
                Spl_ProductCategoryS entity = m_Rep.GetById(model.Name);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              
				entity.Name = model.Name;

				entity.SupID = model.SupID;

				entity.Promoted = model.Promoted;

				entity.Note = model.Note;

				entity.Id = model.Id;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual Spl_ProductCategorySModel GetById(string id)
        {
            if (IsExists(id))
            {
                Spl_ProductCategoryS entity = m_Rep.GetById(id);
                Spl_ProductCategorySModel model = new Spl_ProductCategorySModel();
                              
				model.Name = entity.Name;

				model.SupID = entity.SupID;

				model.Promoted = entity.Promoted;

				model.Note = entity.Note;

				model.Id = entity.Id;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
