
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Spl_Ware
{

    public Spl_Ware()
    {

        this.Spl_Order_Ware = new HashSet<Spl_Order_Ware>();

        this.Spl_Hotware = new HashSet<Spl_Hotware>();

        this.Spl_WareInfo = new HashSet<Spl_WareInfo>();

        this.Spl_Ware_YouHui = new HashSet<Spl_Ware_YouHui>();

    }


    public string Id { get; set; }

    public string Name { get; set; }

    public string ProductCategoryId { get; set; }

    public string Unit { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<int> Stock { get; set; }

    public string Note { get; set; }

    public string Thumbnail { get; set; }

    public string ShowType { get; set; }

    public Nullable<int> WareCount { get; set; }

    public Nullable<bool> WareState { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string Creator { get; set; }

    public Nullable<System.DateTime> UpdateTime { get; set; }

    public string Editor { get; set; }

    public string Description { get; set; }

    public string BrandId { get; set; }

    public Nullable<decimal> PromotionPrice { get; set; }



    public virtual ICollection<Spl_Order_Ware> Spl_Order_Ware { get; set; }

    public virtual ICollection<Spl_Hotware> Spl_Hotware { get; set; }

    public virtual Spl_Brand Spl_Brand { get; set; }

    public virtual Spl_ProductCategoryS Spl_ProductCategoryS { get; set; }

    public virtual ICollection<Spl_WareInfo> Spl_WareInfo { get; set; }

    public virtual ICollection<Spl_Ware_YouHui> Spl_Ware_YouHui { get; set; }

}

}
