
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Spl_Orders
{

    public Spl_Orders()
    {

        this.Spl_Order_Ware = new HashSet<Spl_Order_Ware>();

    }


    public string UserId { get; set; }

    public string OrderNo { get; set; }

    public string Status { get; set; }

    public string AddressId { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<System.DateTime> UpdateTime { get; set; }

    public string Id { get; set; }



    public virtual ICollection<Spl_Order_Ware> Spl_Order_Ware { get; set; }

    public virtual SysUser SysUser { get; set; }

}

}
