
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Spl_Actives
{

    public string id { get; set; }

    public string Title { get; set; }

    public string Cont { get; set; }

    public string Fors { get; set; }

    public Nullable<System.DateTime> BeginDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<bool> IsShow { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<System.DateTime> UpdateTime { get; set; }

}

}
