
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Spl_Ware_YouHui
{

    public string WareId { get; set; }

    public string YouHuiId { get; set; }

    public Nullable<bool> IsUse { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<System.DateTime> Expiry { get; set; }

    public Nullable<bool> IsVoid { get; set; }



    public virtual Spl_Ware Spl_Ware { get; set; }

    public virtual Spl_YouHui Spl_YouHui { get; set; }

}

}
