
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Spl_YouHui
{

    public Spl_YouHui()
    {

        this.Spl_Ware_YouHui = new HashSet<Spl_Ware_YouHui>();

    }


    public string Id { get; set; }

    public string TypeName { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string YContent { get; set; }

    public Nullable<int> Expiry { get; set; }

    public Nullable<double> ShuE { get; set; }



    public virtual ICollection<Spl_Ware_YouHui> Spl_Ware_YouHui { get; set; }

}

}
