//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_WareInfo
    {
        public Spl_WareInfo()
        {
            this.Spl_Ware = new HashSet<Spl_Ware>();
        }
    
        public string id { get; set; }
        public string Picture0 { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string Picture3 { get; set; }
        public string Picture4 { get; set; }
        public string Picture5 { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> ToTop { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Editor { get; set; }
    
        public virtual ICollection<Spl_Ware> Spl_Ware { get; set; }
    }
}
