
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Spl_ProductCategoryS
{

    public Spl_ProductCategoryS()
    {

        this.Spl_Ware = new HashSet<Spl_Ware>();

    }


    public string Id { get; set; }

    public string SonTypeName { get; set; }

    public string SupID { get; set; }

    public Nullable<bool> Promoted { get; set; }

    public string Note { get; set; }

    public string PicShow { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<bool> ToTop { get; set; }

    public string Thumbnail { get; set; }

    public Nullable<int> ShunXu { get; set; }



    public virtual Spl_ProductCategory Spl_ProductCategory { get; set; }

    public virtual ICollection<Spl_Ware> Spl_Ware { get; set; }

}

}
