
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SysAddress
{

    public string UserId { get; set; }

    public string Name { get; set; }

    public string Mobile { get; set; }

    public string Province { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public string House { get; set; }

    public string Typs { get; set; }

    public Nullable<bool> IsDefault { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<System.DateTime> UpdateTime { get; set; }

    public string Id { get; set; }



    public virtual SysUser SysUser { get; set; }

}

}
