
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SysJiaPuBefore
{

    public string Id { get; set; }

    public string uid { get; set; }

    public string tid { get; set; }

    public decimal fje { get; set; }

    public Nullable<bool> isdone { get; set; }

    public Nullable<System.DateTime> createTime { get; set; }

    public string zmp15 { get; set; }

}

}
