//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLevels
    {
        public string id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<float> FirstDiscout { get; set; }
        public Nullable<float> SecondDiscout { get; set; }
        public Nullable<float> ThirdDiscout { get; set; }
        public string Other { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
