
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SysUser
{

    public SysUser()
    {

        this.SysUserConfig = new HashSet<SysUserConfig>();

        this.SysRole = new HashSet<SysRole>();

        this.MIS_Article_Comment = new HashSet<MIS_Article_Comment>();

        this.Flow_FormContent = new HashSet<Flow_FormContent>();

        this.Flow_FormContentStepCheckState = new HashSet<Flow_FormContentStepCheckState>();

        this.WC_OfficalAccounts = new HashSet<WC_OfficalAccounts>();

        this.SysPurchaseHistory = new HashSet<SysPurchaseHistory>();

        this.SysWallet = new HashSet<SysWallet>();

        this.SysErCi = new HashSet<SysErCi>();

        this.SysAddress = new HashSet<SysAddress>();

        this.Spl_Orders = new HashSet<Spl_Orders>();

        this.SysPerson = new HashSet<SysPerson>();

        this.MIS_Article = new HashSet<MIS_Article>();

        this.MIS_Article1 = new HashSet<MIS_Article>();

        this.SysJiaPu = new HashSet<SysJiaPu>();

        this.SysFirst = new HashSet<SysFirst>();

        this.SysTuiUser = new HashSet<SysTuiUser>();

        this.SysTuiUser1 = new HashSet<SysTuiUser>();

    }


    public string Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string TrueName { get; set; }

    public string Card { get; set; }

    public string MobileNumber { get; set; }

    public string PhoneNumber { get; set; }

    public string QQ { get; set; }

    public string EmailAddress { get; set; }

    public string OtherContact { get; set; }

    public string Province { get; set; }

    public string City { get; set; }

    public string Village { get; set; }

    public string Address { get; set; }

    public bool State { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string CreatePerson { get; set; }

    public string Sex { get; set; }

    public Nullable<System.DateTime> Birthday { get; set; }

    public Nullable<System.DateTime> JoinDate { get; set; }

    public string Marital { get; set; }

    public string Political { get; set; }

    public string Nationality { get; set; }

    public string Native { get; set; }

    public string School { get; set; }

    public string Professional { get; set; }

    public string Degree { get; set; }

    public string DepId { get; set; }

    public string PosId { get; set; }

    public string Expertise { get; set; }

    public Nullable<bool> JobState { get; set; }

    public string Photo { get; set; }

    public string Attach { get; set; }

    public string Lead { get; set; }

    public string LeadName { get; set; }

    public bool IsSelLead { get; set; }

    public bool IsReportCalendar { get; set; }

    public bool IsSecretary { get; set; }

    public string HomePhone { get; set; }

    public string WXID { get; set; }

    public string Signature { get; set; }

    public string QRCode { get; set; }

    public string IdentityCardFile { get; set; }

    public string IdentityCardBackFile { get; set; }

    public Nullable<bool> IsAuth { get; set; }

    public string AuditStatus { get; set; }

    public string Note { get; set; }

    public string SortCode { get; set; }

    public string RecommendID { get; set; }

    public Nullable<System.DateTime> RecommendTime { get; set; }

    public string EditorID { get; set; }

    public Nullable<System.DateTime> UpdateTime { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string Questions { get; set; }

    public string Answer { get; set; }

    public string LastLoginIP { get; set; }

    public Nullable<System.DateTime> LastLoginTime { get; set; }

    public string CurrentLoginIP { get; set; }

    public Nullable<System.DateTime> CurrentLoginTime { get; set; }

    public Nullable<System.DateTime> LastPasswdTime { get; set; }

    public string Recommendor { get; set; }

    public string TuiCode { get; set; }

    public Nullable<int> TuiCount { get; set; }

    public Nullable<int> TuiDownloadCount { get; set; }



    public virtual ICollection<SysUserConfig> SysUserConfig { get; set; }

    public virtual ICollection<SysRole> SysRole { get; set; }

    public virtual ICollection<MIS_Article_Comment> MIS_Article_Comment { get; set; }

    public virtual ICollection<Flow_FormContent> Flow_FormContent { get; set; }

    public virtual ICollection<Flow_FormContentStepCheckState> Flow_FormContentStepCheckState { get; set; }

    public virtual SysPosition SysPosition { get; set; }

    public virtual SysStruct SysStruct { get; set; }

    public virtual ICollection<WC_OfficalAccounts> WC_OfficalAccounts { get; set; }

    public virtual ICollection<SysPurchaseHistory> SysPurchaseHistory { get; set; }

    public virtual ICollection<SysWallet> SysWallet { get; set; }

    public virtual ICollection<SysErCi> SysErCi { get; set; }

    public virtual ICollection<SysAddress> SysAddress { get; set; }

    public virtual ICollection<Spl_Orders> Spl_Orders { get; set; }

    public virtual ICollection<SysPerson> SysPerson { get; set; }

    public virtual ICollection<MIS_Article> MIS_Article { get; set; }

    public virtual ICollection<MIS_Article> MIS_Article1 { get; set; }

    public virtual ICollection<SysJiaPu> SysJiaPu { get; set; }

    public virtual ICollection<SysFirst> SysFirst { get; set; }

    public virtual ICollection<SysTuiUser> SysTuiUser { get; set; }

    public virtual ICollection<SysTuiUser> SysTuiUser1 { get; set; }

}

}
