//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductImg = new HashSet<ProductImg>();
        }
    
        public int Id { get; set; }
        public int TypeID { get; set; }
        public int BrandID { get; set; }
        public string ProName { get; set; }
        public string Description { get; set; }
        public string Attribute { get; set; }
        public string Overview { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Promotion { get; set; }
        public byte[] ImgData { get; set; }
        public string ImgMimeType { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<ProductImg> ProductImg { get; set; }
        public virtual ProductTypeS ProductTypeS { get; set; }
    }
}
