//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Sys
{
	public class Virtual_SysJiaPuModel
	{
			public virtual string id { get; set; }
			public virtual string UserId { get; set; }
			public virtual string ParentId { get; set; }
			public virtual string PPId { get; set; }
			public virtual string ZiMu { get; set; }
			public virtual string ShuZi { get; set; }
			public virtual Nullable<int> ErZiShu { get; set; }
			public virtual Nullable<decimal> FirstJinE { get; set; }
			public virtual int LevelId { get; set; }
			public virtual string ZMP15 { get; set; }
			public virtual string ZMPA2 { get; set; }
			public virtual string ZMPB2 { get; set; }
			public virtual string ZMPC2 { get; set; }
			public virtual string ZMPD2 { get; set; }
			public virtual string ZMPE2 { get; set; }
			public virtual string ZMPF2 { get; set; }
			public virtual string ZMPG2 { get; set; }
			public virtual string ZMPH2 { get; set; }
			public virtual string ZMPI2 { get; set; }
			public virtual string ZMPJ2 { get; set; }
			public virtual string Comment { get; set; }
			public virtual Nullable<System.DateTime> CreateTime { get; set; }
			public virtual Nullable<System.DateTime> UpdateTime { get; set; }
			public virtual string TopId { get; set; }
			public virtual string TId { get; set; }
		}
}
