
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using Apps.Models;
using System;
namespace Apps.Models.Spl
{
	public class Virtual_Spl_WareInfoModel
	{
		
	public virtual string Picture0 { get; set; }
		
	public virtual string Picture1 { get; set; }
		
	public virtual string Picture2 { get; set; }
		
	public virtual string Picture3 { get; set; }
		
	public virtual string Picture4 { get; set; }
		
	public virtual string Picture5 { get; set; }
		
	public virtual string Detail { get; set; }
		
	public virtual Nullable<bool> ToTop { get; set; }
		
	public virtual Nullable<System.DateTime> CreateTime { get; set; }
		
	public virtual string Creator { get; set; }
		
	public virtual Nullable<System.DateTime> UpdateTime { get; set; }
		
	public virtual string Editor { get; set; }
		
	public virtual string WareId { get; set; }
		
	public virtual string Id { get; set; }
		
}

}
