
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using Apps.Models;
using System;
namespace Apps.Models.Sys
{
	public class Virtual_SysPurchaseHistoryModel
	{
		
	public virtual string UserId { get; set; }
		
	public virtual Nullable<decimal> ShouRu { get; set; }
		
	public virtual string Froms { get; set; }
		
	public virtual Nullable<System.DateTime> CreateTime { get; set; }
		
	public virtual string Note { get; set; }
		
	public virtual Nullable<bool> IsShow { get; set; }
		
	public virtual string Id { get; set; }
		
}

}
