
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using Apps.Models;
using System;
namespace Apps.Models.Sys
{
	public class Virtual_SysUserModel
	{
		
	public virtual string Id { get; set; }
		
	public virtual string UserName { get; set; }
		
	public virtual string Password { get; set; }
		
	public virtual string TrueName { get; set; }
		
	public virtual string Card { get; set; }
		
	public virtual string MobileNumber { get; set; }
		
	public virtual string PhoneNumber { get; set; }
		
	public virtual string QQ { get; set; }
		
	public virtual string EmailAddress { get; set; }
		
	public virtual string OtherContact { get; set; }
		
	public virtual string Province { get; set; }
		
	public virtual string City { get; set; }
		
	public virtual string Village { get; set; }
		
	public virtual string Address { get; set; }
		
	public virtual bool State { get; set; }
		
	public virtual Nullable<System.DateTime> CreateTime { get; set; }
		
	public virtual string CreatePerson { get; set; }
		
	public virtual string Sex { get; set; }
		
	public virtual Nullable<System.DateTime> Birthday { get; set; }
		
	public virtual Nullable<System.DateTime> JoinDate { get; set; }
		
	public virtual string Marital { get; set; }
		
	public virtual string Political { get; set; }
		
	public virtual string Nationality { get; set; }
		
	public virtual string Native { get; set; }
		
	public virtual string School { get; set; }
		
	public virtual string Professional { get; set; }
		
	public virtual string Degree { get; set; }
		
	public virtual string DepId { get; set; }
		
	public virtual string PosId { get; set; }
		
	public virtual string Expertise { get; set; }
		
	public virtual Nullable<bool> JobState { get; set; }
		
	public virtual string Photo { get; set; }
		
	public virtual string Attach { get; set; }
		
	public virtual string Lead { get; set; }
		
	public virtual string LeadName { get; set; }
		
	public virtual Nullable<bool> IsSelLead { get; set; }
		
	public virtual Nullable<bool> IsReportCalendar { get; set; }
		
	public virtual Nullable<bool> IsSecretary { get; set; }
		
	public virtual string HomePhone { get; set; }
		
	public virtual string WXID { get; set; }
		
	public virtual string Signature { get; set; }
		
	public virtual string QRCode { get; set; }
		
	public virtual string IdentityCardFile { get; set; }
		
	public virtual string IdentityCardBackFile { get; set; }
		
	public virtual Nullable<bool> IsAuth { get; set; }
		
	public virtual string AuditStatus { get; set; }
		
	public virtual string Note { get; set; }
		
	public virtual string SortCode { get; set; }
		
	public virtual string RecommendID { get; set; }
		
	public virtual Nullable<System.DateTime> RecommendTime { get; set; }
		
	public virtual string EditorID { get; set; }
		
	public virtual Nullable<System.DateTime> UpdateTime { get; set; }
		
	public virtual Nullable<bool> IsDeleted { get; set; }
		
	public virtual string Questions { get; set; }
		
	public virtual string Answer { get; set; }
		
	public virtual string LastLoginIP { get; set; }
		
	public virtual Nullable<System.DateTime> LastLoginTime { get; set; }
		
	public virtual string CurrentLoginIP { get; set; }
		
	public virtual Nullable<System.DateTime> CurrentLoginTime { get; set; }
		
	public virtual Nullable<System.DateTime> LastPasswdTime { get; set; }
		
	public virtual string Recommendor { get; set; }
		
	public virtual string TuiCode { get; set; }
		
	public virtual Nullable<int> TuiCount { get; set; }
		
	public virtual Nullable<int> TuiDownloadCount { get; set; }
		
}

}
