
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using Apps.Models;
using System;
namespace Apps.Models.Sys
{
	public class Virtual_SysJiaPuBeforeModel
	{
		
	public virtual string Id { get; set; }
		
	public virtual string uid { get; set; }
		
	public virtual string tid { get; set; }
		
	public virtual decimal fje { get; set; }
		
	public virtual Nullable<bool> isdone { get; set; }
		
	public virtual Nullable<System.DateTime> createTime { get; set; }
		
	public virtual string zmp15 { get; set; }
		
}

}
