
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using Apps.Models;
using System;
namespace Apps.Models.Sys
{
	public class Virtual_SysDcitTpeModel
	{
		
	public virtual string Id { get; set; }
		
	public virtual string Name { get; set; }
		
	public virtual string Remarek { get; set; }
		
	public virtual string SortCode { get; set; }
		
	public virtual string Creator { get; set; }
		
	public virtual Nullable<System.DateTime> CreateTime { get; set; }
		
	public virtual byte[] Editor { get; set; }
		
	public virtual Nullable<System.DateTime> EditTime { get; set; }
		
	public virtual string Pid { get; set; }
		
}

}
