
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using Apps.Models;
using System;
namespace Apps.Models.Sys
{
	public class Virtual_SysMessageModel
	{
		
	public virtual string id { get; set; }
		
	public virtual string Title { get; set; }
		
	public virtual string Cont { get; set; }
		
	public virtual string Category { get; set; }
		
	public virtual string FromWho { get; set; }
		
	public virtual string ToWho { get; set; }
		
	public virtual Nullable<System.DateTime> CreateTime { get; set; }
		
	public virtual Nullable<System.DateTime> UpdateTime { get; set; }
		
}

}
