//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Spl
{
	public class Virtual_Spl_WareModel
	{
			public virtual string id { get; set; }
			public virtual string Name { get; set; }
			public virtual string ProductCategoryId { get; set; }
			public virtual string Unit { get; set; }
			public virtual Nullable<decimal> OriginPrice { get; set; }
			public virtual Nullable<decimal> Price { get; set; }
			public virtual Nullable<int> Stock { get; set; }
			public virtual string Note { get; set; }
			public virtual string Thumbnail { get; set; }
			public virtual string ShowType { get; set; }
			public virtual string WareInfoId { get; set; }
			public virtual Nullable<int> WareCount { get; set; }
			public virtual Nullable<bool> WareState { get; set; }
			public virtual Nullable<System.DateTime> CreateTime { get; set; }
			public virtual string Creator { get; set; }
			public virtual Nullable<System.DateTime> UpdateTime { get; set; }
			public virtual string Editor { get; set; }
			public virtual string Description { get; set; }
		}
}
