//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Spl
{
	public class Virtual_Spl_ActivesModel
	{
			public virtual string id { get; set; }
			public virtual string Title { get; set; }
			public virtual string Cont { get; set; }
			public virtual string Fors { get; set; }
			public virtual Nullable<System.DateTime> BeginDate { get; set; }
			public virtual Nullable<System.DateTime> EndDate { get; set; }
			public virtual Nullable<bool> IsShow { get; set; }
			public virtual Nullable<System.DateTime> CreateTime { get; set; }
			public virtual Nullable<System.DateTime> UpdateTime { get; set; }
		}
}
