
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using Apps.Models;
using System;
namespace Apps.Models.Sys
{
	public class Virtual_SysAddressModel
	{
		
	public virtual string Id { get; set; }
		
	public virtual string UserId { get; set; }
		
	public virtual string Name { get; set; }
		
	public virtual string Mobile { get; set; }
		
	public virtual string Province { get; set; }
		
	public virtual string City { get; set; }
		
	public virtual string Street { get; set; }
		
	public virtual string House { get; set; }
		
	public virtual string Typs { get; set; }
		
	public virtual Nullable<bool> IsDefault { get; set; }
		
	public virtual Nullable<System.DateTime> CreateTime { get; set; }
		
	public virtual Nullable<System.DateTime> UpdateTime { get; set; }
		
}

}
