//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Models.Sys;
namespace Apps.BLL
{
	public class Virtual_SysDictDataBLL
	{
        [Dependency]
        public ISysDictDataRepository m_Rep { get; set; }

		public virtual List<SysDictDataModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysDictData> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.id.Contains(queryStr)
								|| a.DictType_Id.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.DicValue.Contains(queryStr)
								|| a.Remark.Contains(queryStr)
								|| a.SortCode.Contains(queryStr)
								|| a.Creator.Contains(queryStr)
								
								|| a.Editor.Contains(queryStr)
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<SysDictDataModel> CreateModelList(ref IQueryable<SysDictData> queryData)
        {

            List<SysDictDataModel> modelList = (from r in queryData
                                              select new SysDictDataModel
                                              {
													id = r.id,
													DictType_Id = r.DictType_Id,
													Name = r.Name,
													DicValue = r.DicValue,
													Remark = r.Remark,
													SortCode = r.SortCode,
													Creator = r.Creator,
													CreateTime = r.CreateTime,
													Editor = r.Editor,
													EditTime = r.EditTime,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysDictDataModel model)
        {
            try
            {
                SysDictData entity = m_Rep.GetById(model.id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysDictData();
               				entity.id = model.id;
				entity.DictType_Id = model.DictType_Id;
				entity.Name = model.Name;
				entity.DicValue = model.DicValue;
				entity.Remark = model.Remark;
				entity.SortCode = model.SortCode;
				entity.Creator = model.Creator;
				entity.CreateTime = model.CreateTime;
				entity.Editor = model.Editor;
				entity.EditTime = model.EditTime;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysDictDataModel model)
        {
            try
            {
                SysDictData entity = m_Rep.GetById(model.id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.id = model.id;
				entity.DictType_Id = model.DictType_Id;
				entity.Name = model.Name;
				entity.DicValue = model.DicValue;
				entity.Remark = model.Remark;
				entity.SortCode = model.SortCode;
				entity.Creator = model.Creator;
				entity.CreateTime = model.CreateTime;
				entity.Editor = model.Editor;
				entity.EditTime = model.EditTime;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysDictDataModel GetById(string id)
        {
            if (IsExists(id))
            {
                SysDictData entity = m_Rep.GetById(id);
                SysDictDataModel model = new SysDictDataModel();
                              				model.id = entity.id;
				model.DictType_Id = entity.DictType_Id;
				model.Name = entity.Name;
				model.DicValue = entity.DicValue;
				model.Remark = entity.Remark;
				model.SortCode = entity.SortCode;
				model.Creator = entity.Creator;
				model.CreateTime = entity.CreateTime;
				model.Editor = entity.Editor;
				model.EditTime = entity.EditTime;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
