
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Models.Sys;
namespace Apps.BLL
{
	public class Virtual_SysProductBLL
	{
        [Dependency]
        public ISysProductRepository m_Rep { get; set; }

		public virtual List<SysProductModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysProduct> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
				
				a=>a.Id.Contains(queryStr)
				

				|| a.Name.Contains(queryStr)
				

				|| a.Code.Contains(queryStr)
				

				
				

				
				

				|| a.Color.Contains(queryStr)
				

				
				

				|| a.CategoryId.Contains(queryStr)
				

				
				

				|| a.CreateBy.Contains(queryStr)
				

				);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<SysProductModel> CreateModelList(ref IQueryable<SysProduct> queryData)
        {

            List<SysProductModel> modelList = (from r in queryData
                                              select new SysProductModel
                                              {

													Id = r.Id,

													Name = r.Name,

													Code = r.Code,

													Price = r.Price,

													CostPrice = r.CostPrice,

													Color = r.Color,

													Number = r.Number,

													CategoryId = r.CategoryId,

													CreateTime = r.CreateTime,

													CreateBy = r.CreateBy,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysProductModel model)
        {
            try
            {
                SysProduct entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysProduct();
               
				entity.Id = model.Id;

				entity.Name = model.Name;

				entity.Code = model.Code;

				entity.Price = model.Price;

				entity.CostPrice = model.CostPrice;

				entity.Color = model.Color;

				entity.Number = model.Number;

				entity.CategoryId = model.CategoryId;

				entity.CreateTime = model.CreateTime;

				entity.CreateBy = model.CreateBy;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysProductModel model)
        {
            try
            {
                SysProduct entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              
				entity.Id = model.Id;

				entity.Name = model.Name;

				entity.Code = model.Code;

				entity.Price = model.Price;

				entity.CostPrice = model.CostPrice;

				entity.Color = model.Color;

				entity.Number = model.Number;

				entity.CategoryId = model.CategoryId;

				entity.CreateTime = model.CreateTime;

				entity.CreateBy = model.CreateBy;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysProductModel GetById(string id)
        {
            if (IsExists(id))
            {
                SysProduct entity = m_Rep.GetById(id);
                SysProductModel model = new SysProductModel();
                              
				model.Id = entity.Id;

				model.Name = entity.Name;

				model.Code = entity.Code;

				model.Price = entity.Price;

				model.CostPrice = entity.CostPrice;

				model.Color = entity.Color;

				model.Number = entity.Number;

				model.CategoryId = entity.CategoryId;

				model.CreateTime = entity.CreateTime;

				model.CreateBy = entity.CreateBy;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
