
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Models.Sys;
namespace Apps.BLL
{
	public class Virtual_SysErCiBLL
	{
        [Dependency]
        public ISysErCiRepository m_Rep { get; set; }

		public virtual List<SysErCiModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysErCi> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
				
				a=>a.UserId.Contains(queryStr)
				

				|| a.OrderId.Contains(queryStr)
				

				
				

				
				

				|| a.Note.Contains(queryStr)
				

				|| a.Id.Contains(queryStr)
				

				);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<SysErCiModel> CreateModelList(ref IQueryable<SysErCi> queryData)
        {

            List<SysErCiModel> modelList = (from r in queryData
                                              select new SysErCiModel
                                              {

													UserId = r.UserId,

													OrderId = r.OrderId,

													JinE = r.JinE,

													CreateTime = r.CreateTime,

													Note = r.Note,

													Id = r.Id,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysErCiModel model)
        {
            try
            {
                SysErCi entity = m_Rep.GetById(model.UserId);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysErCi();
               
				entity.UserId = model.UserId;

				entity.OrderId = model.OrderId;

				entity.JinE = model.JinE;

				entity.CreateTime = model.CreateTime;

				entity.Note = model.Note;

				entity.Id = model.Id;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysErCiModel model)
        {
            try
            {
                SysErCi entity = m_Rep.GetById(model.UserId);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              
				entity.UserId = model.UserId;

				entity.OrderId = model.OrderId;

				entity.JinE = model.JinE;

				entity.CreateTime = model.CreateTime;

				entity.Note = model.Note;

				entity.Id = model.Id;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysErCiModel GetById(string id)
        {
            if (IsExists(id))
            {
                SysErCi entity = m_Rep.GetById(id);
                SysErCiModel model = new SysErCiModel();
                              
				model.UserId = entity.UserId;

				model.OrderId = entity.OrderId;

				model.JinE = entity.JinE;

				model.CreateTime = entity.CreateTime;

				model.Note = entity.Note;

				model.Id = entity.Id;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
