
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Models.Sys;
namespace Apps.BLL
{
	public class Virtual_SysMessageBLL
	{
        [Dependency]
        public ISysMessageRepository m_Rep { get; set; }

		public virtual List<SysMessageModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysMessage> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
				
				a=>a.Id.Contains(queryStr)
				

				|| a.Title.Contains(queryStr)
				

				|| a.Cont.Contains(queryStr)
				

				|| a.Category.Contains(queryStr)
				

				|| a.FromWho.Contains(queryStr)
				

				|| a.ToWho.Contains(queryStr)
				

				
				

				
				

				
				

				);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<SysMessageModel> CreateModelList(ref IQueryable<SysMessage> queryData)
        {

            List<SysMessageModel> modelList = (from r in queryData
                                              select new SysMessageModel
                                              {

													Id = r.Id,

													Title = r.Title,

													Cont = r.Cont,

													Category = r.Category,

													FromWho = r.FromWho,

													ToWho = r.ToWho,

													CreateTime = r.CreateTime,

													UpdateTime = r.UpdateTime,

													IsRead = r.IsRead,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysMessageModel model)
        {
            try
            {
                SysMessage entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysMessage();
               
				entity.Id = model.Id;

				entity.Title = model.Title;

				entity.Cont = model.Cont;

				entity.Category = model.Category;

				entity.FromWho = model.FromWho;

				entity.ToWho = model.ToWho;

				entity.CreateTime = model.CreateTime;

				entity.UpdateTime = model.UpdateTime;

				entity.IsRead = model.IsRead;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysMessageModel model)
        {
            try
            {
                SysMessage entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              
				entity.Id = model.Id;

				entity.Title = model.Title;

				entity.Cont = model.Cont;

				entity.Category = model.Category;

				entity.FromWho = model.FromWho;

				entity.ToWho = model.ToWho;

				entity.CreateTime = model.CreateTime;

				entity.UpdateTime = model.UpdateTime;

				entity.IsRead = model.IsRead;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysMessageModel GetById(string id)
        {
            if (IsExists(id))
            {
                SysMessage entity = m_Rep.GetById(id);
                SysMessageModel model = new SysMessageModel();
                              
				model.Id = entity.Id;

				model.Title = entity.Title;

				model.Cont = entity.Cont;

				model.Category = entity.Category;

				model.FromWho = entity.FromWho;

				model.ToWho = entity.ToWho;

				model.CreateTime = entity.CreateTime;

				model.UpdateTime = entity.UpdateTime;

				model.IsRead = entity.IsRead;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
