
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Models.Sys;
namespace Apps.BLL
{
	public class Virtual_SysPurchaseHistoryBLL
	{
        [Dependency]
        public ISysPurchaseHistoryRepository m_Rep { get; set; }

		public virtual List<SysPurchaseHistoryModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysPurchaseHistory> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
				
				a=>a.Id.Contains(queryStr)
				

				|| a.UserId.Contains(queryStr)
				

				
				

				|| a.Froms.Contains(queryStr)
				

				
				

				|| a.Note.Contains(queryStr)
				

				
				

				);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<SysPurchaseHistoryModel> CreateModelList(ref IQueryable<SysPurchaseHistory> queryData)
        {

            List<SysPurchaseHistoryModel> modelList = (from r in queryData
                                              select new SysPurchaseHistoryModel
                                              {

													Id = r.Id,

													UserId = r.UserId,

													ShouRu = r.ShouRu,

													Froms = r.Froms,

													CreateTime = r.CreateTime,

													Note = r.Note,

													IsShow = r.IsShow,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysPurchaseHistoryModel model)
        {
            try
            {
                SysPurchaseHistory entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysPurchaseHistory();
               
				entity.Id = model.Id;

				entity.UserId = model.UserId;

				entity.ShouRu = model.ShouRu;

				entity.Froms = model.Froms;

				entity.CreateTime = model.CreateTime;

				entity.Note = model.Note;

				entity.IsShow = model.IsShow;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysPurchaseHistoryModel model)
        {
            try
            {
                SysPurchaseHistory entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              
				entity.Id = model.Id;

				entity.UserId = model.UserId;

				entity.ShouRu = model.ShouRu;

				entity.Froms = model.Froms;

				entity.CreateTime = model.CreateTime;

				entity.Note = model.Note;

				entity.IsShow = model.IsShow;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysPurchaseHistoryModel GetById(string id)
        {
            if (IsExists(id))
            {
                SysPurchaseHistory entity = m_Rep.GetById(id);
                SysPurchaseHistoryModel model = new SysPurchaseHistoryModel();
                              
				model.Id = entity.Id;

				model.UserId = entity.UserId;

				model.ShouRu = entity.ShouRu;

				model.Froms = entity.Froms;

				model.CreateTime = entity.CreateTime;

				model.Note = entity.Note;

				model.IsShow = entity.IsShow;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
