//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Models.Sys;
namespace Apps.BLL
{
	public class Virtual_SysWalletBLL
	{
        [Dependency]
        public ISysWalletRepository m_Rep { get; set; }

		public virtual List<SysWalletModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysWallet> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.id.Contains(queryStr)
								|| a.UserId.Contains(queryStr)
								
								|| a.Froms.Contains(queryStr)
								
								|| a.Note.Contains(queryStr)
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<SysWalletModel> CreateModelList(ref IQueryable<SysWallet> queryData)
        {

            List<SysWalletModel> modelList = (from r in queryData
                                              select new SysWalletModel
                                              {
													id = r.id,
													UserId = r.UserId,
													Balance = r.Balance,
													Froms = r.Froms,
													JieYu = r.JieYu,
													Note = r.Note,
													CreateTime = r.CreateTime,
													UpdateTime = r.UpdateTime,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysWalletModel model)
        {
            try
            {
                SysWallet entity = m_Rep.GetById(model.id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysWallet();
               				entity.id = model.id;
				entity.UserId = model.UserId;
				entity.Balance = model.Balance;
				entity.Froms = model.Froms;
				entity.JieYu = model.JieYu;
				entity.Note = model.Note;
				entity.CreateTime = model.CreateTime;
				entity.UpdateTime = model.UpdateTime;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysWalletModel model)
        {
            try
            {
                SysWallet entity = m_Rep.GetById(model.id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.id = model.id;
				entity.UserId = model.UserId;
				entity.Balance = model.Balance;
				entity.Froms = model.Froms;
				entity.JieYu = model.JieYu;
				entity.Note = model.Note;
				entity.CreateTime = model.CreateTime;
				entity.UpdateTime = model.UpdateTime;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysWalletModel GetById(string id)
        {
            if (IsExists(id))
            {
                SysWallet entity = m_Rep.GetById(id);
                SysWalletModel model = new SysWalletModel();
                              				model.id = entity.id;
				model.UserId = entity.UserId;
				model.Balance = entity.Balance;
				model.Froms = entity.Froms;
				model.JieYu = entity.JieYu;
				model.Note = entity.Note;
				model.CreateTime = entity.CreateTime;
				model.UpdateTime = entity.UpdateTime;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
