//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Models.Sys;
namespace Apps.BLL
{
	public class Virtual_SysDcitTpeBLL
	{
        [Dependency]
        public ISysDcitTpeRepository m_Rep { get; set; }

		public virtual List<SysDcitTpeModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysDcitTpe> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.id.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.Remarek.Contains(queryStr)
								|| a.SortCode.Contains(queryStr)
								|| a.Creator.Contains(queryStr)
								
								
								
								|| a.Pid.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<SysDcitTpeModel> CreateModelList(ref IQueryable<SysDcitTpe> queryData)
        {

            List<SysDcitTpeModel> modelList = (from r in queryData
                                              select new SysDcitTpeModel
                                              {
													id = r.id,
													Name = r.Name,
													Remarek = r.Remarek,
													SortCode = r.SortCode,
													Creator = r.Creator,
													CreateTime = r.CreateTime,
													Editor = r.Editor,
													EditTime = r.EditTime,
													Pid = r.Pid,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysDcitTpeModel model)
        {
            try
            {
                SysDcitTpe entity = m_Rep.GetById(model.id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysDcitTpe();
               				entity.id = model.id;
				entity.Name = model.Name;
				entity.Remarek = model.Remarek;
				entity.SortCode = model.SortCode;
				entity.Creator = model.Creator;
				entity.CreateTime = model.CreateTime;
				entity.Editor = model.Editor;
				entity.EditTime = model.EditTime;
				entity.Pid = model.Pid;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysDcitTpeModel model)
        {
            try
            {
                SysDcitTpe entity = m_Rep.GetById(model.id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.id = model.id;
				entity.Name = model.Name;
				entity.Remarek = model.Remarek;
				entity.SortCode = model.SortCode;
				entity.Creator = model.Creator;
				entity.CreateTime = model.CreateTime;
				entity.Editor = model.Editor;
				entity.EditTime = model.EditTime;
				entity.Pid = model.Pid;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysDcitTpeModel GetById(string id)
        {
            if (IsExists(id))
            {
                SysDcitTpe entity = m_Rep.GetById(id);
                SysDcitTpeModel model = new SysDcitTpeModel();
                              				model.id = entity.id;
				model.Name = entity.Name;
				model.Remarek = entity.Remarek;
				model.SortCode = entity.SortCode;
				model.Creator = entity.Creator;
				model.CreateTime = entity.CreateTime;
				model.Editor = entity.Editor;
				model.EditTime = entity.EditTime;
				model.Pid = entity.Pid;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
