//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.DAL;
using Apps.WC.IDAL;
using System;
namespace Apps.WC.DAL
{
	public partial class WC_Table_1Repository:BaseRepository<WC_Table_1>,IWC_Table_1Repository,IDisposable
	{
	    public WC_Table_1Repository(DBContainer db):base(db)
        {
        
        }
     
	}
}
